<?php
    echo <<<HTML
    <table>
        <tr>
            <td>⬛️</td>
            <td>⬜️</td>
            <td>⬛️</td>
        </tr>
        <tr>
            <td>⬜️</td>
            <td>⬛️</td>
            <td>⬜️</td>
        </tr>
        <tr>
            <td>⬛️</td>
            <td>⬜️</td>
            <td>⬛️</td>
    </table>
    HTML;
?>